[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.0.0-alpha.1", features = ["v4"] }
image = { version = "0.23.14", features = ["pnm", "png"] }

